"""Scenario 8: dynamic Send workers generated by a conditional router."""

from agentflow import Checkpointer

from .common import banner, build_configured_graph


def run_dynamic_send() -> None:
    banner("场景 8 — 动态 Send/worker：router 动态生成同名 worker 实例")
    cp = Checkpointer()
    app = build_configured_graph("dynamic_send", cp)
    res = app.invoke({}, thread_id="dynamic-send")
    assert res.status == "completed"
    print(f"\n→ status={res.status}, step={res.step}")
    print(f"  fanout keys: {sorted(res.state.get('fanout', {}).keys())}")
    for line in res.state.get("log", []):
        print(f"    {line}")


if __name__ == "__main__":
    run_dynamic_send()